feat(20672): add error message about title
rollun-com/swagger-editor pull request #16
Opened 2023-08-07 14:37 UTC by kostrov-rollun

2023-08-07 15:49 UTC, rollun-com requested changes

2023-08-07 15:49 UTC, rollun-com commented on src/plugins/validate-rollun-semantic/validators.js
> +    if(url.split("/openapi/")[1].split("/")[0] !== (JSONSpec.info.title || "EmptyTitle")) {
можно заінлайнити -
```
JSONSpec.servers.findIndex(({ url }) => url.split("/openapi/")[1].split("/")[0] !== (JSONSpec.info.title || "EmptyTitle"))
```

2023-08-10 13:26 UTC, rollun-com requested changes

2023-08-10 13:26 UTC, rollun-com commented on src/plugins/validate-rollun-semantic/validators.js
> +    const titleFromUrl = url.split("/openapi/")[1].split("/")[0]
можеш переформатувати цей код, в більш читаемий формат, бо не дуже зрозуміло що відбуваеться, думаю краще заюзати RegExp і винести це в окрему функу, і юзати її скрізь

2023-08-14 15:54 UTC, rollun-com requested changes

2023-08-14 15:54 UTC, rollun-com commented on src/plugins/validate-rollun-semantic/validators.js
> +  const invalidServerTitleIndex = JSONSpec.servers.findIndex(({ url }) => url.split("/openapi/")[1].split("/")[0] !== (JSONSpec.info.title || "EmptyTitle"))
тут теж треба заюзати функу)

2023-08-15 06:27 UTC, kostrov-rollun commented on src/plugins/validate-rollun-semantic/validators.js
> +  const invalidServerTitleIndex = JSONSpec.servers.findIndex(({ url }) => url.split("/openapi/")[1].split("/")[0] !== (JSONSpec.info.title || "EmptyTitle"))
не помітив, пофіксив

2023-08-16 14:52 UTC, rollun-com approved these changes

2023-08-16 14:56 UTC, merged